In [4]:
## CALLING LIBRARIES

import numpy as np
import pandas as pd
import scipy.stats as stats
import math
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.stats as stats
from scipy.stats             import ttest_1samp,ttest_ind, wilcoxon
from statsmodels.stats.power import ttest_power
import matplotlib.pyplot     as     plt

In [5]:
a=[107,73,68,97,76,79,94,59,98,57,54,65,71,70,84,88,62,61,79,98,66,62,79,86,68,74,61,82,65,98,62,116,65,88,64,79,78,79,77,86,74,85,73,80,68,78,89,72,58,69,92,78,88,77,103,88,63,68,88,81,75,90,62,89,71,71,74,70,74,70,65,81,75,62,94,71,85,84,83,63,81,62,79,83,93,61,65,62,92,65,83,70,70,81,77,72,84,67,59,58,78,66,66,94,77,63,66,75,68,76,90,78,71,101,78,43,59,67,61,71,96,75,64,76,72,77,74,65,82,86,66,86,96,89,81,71,85,99,59,92,68,72,77,60,87,84,75,77,51,45,85,67,87,80,84,93,69,76,89,75,83,68,72,67,92,89,82,96,77,102,74,91,76,83,66,68,61,73,72,76,73,77,79,94,63,59,62,71,81,65,73,63,63,89,82,64,85,92,64,73]
(a-np.mean(a))/np.std(a)

array([ 2.57592034, -0.24928261, -0.66475364,  1.7449783 ,  0.        ,
        0.24928261,  1.49569568, -1.41260148,  1.8280725 , -1.57878989,
       -1.8280725 , -0.91403625, -0.41547102, -0.49856523,  0.66475364,
        0.99713045, -1.16331886, -1.24641307,  0.24928261,  1.8280725 ,
       -0.83094205, -1.16331886,  0.24928261,  0.83094205, -0.66475364,
       -0.16618841, -1.24641307,  0.49856523, -0.91403625,  1.8280725 ,
       -1.16331886,  3.32376818, -0.91403625,  0.99713045, -0.99713045,
        0.24928261,  0.16618841,  0.24928261,  0.0830942 ,  0.83094205,
       -0.16618841,  0.74784784, -0.24928261,  0.33237682, -0.66475364,
        0.16618841,  1.08022466, -0.33237682, -1.49569568, -0.58165943,
        1.32950727,  0.16618841,  0.99713045,  0.0830942 ,  2.24354352,
        0.99713045, -1.08022466, -0.66475364,  0.99713045,  0.41547102,
       -0.0830942 ,  1.16331886, -1.16331886,  1.08022466, -0.41547102,
       -0.41547102, -0.16618841, -0.49856523, -0.16618841, -0.49

In [6]:
stats.zscore(a)

array([ 2.57592034, -0.24928261, -0.66475364,  1.7449783 ,  0.        ,
        0.24928261,  1.49569568, -1.41260148,  1.8280725 , -1.57878989,
       -1.8280725 , -0.91403625, -0.41547102, -0.49856523,  0.66475364,
        0.99713045, -1.16331886, -1.24641307,  0.24928261,  1.8280725 ,
       -0.83094205, -1.16331886,  0.24928261,  0.83094205, -0.66475364,
       -0.16618841, -1.24641307,  0.49856523, -0.91403625,  1.8280725 ,
       -1.16331886,  3.32376818, -0.91403625,  0.99713045, -0.99713045,
        0.24928261,  0.16618841,  0.24928261,  0.0830942 ,  0.83094205,
       -0.16618841,  0.74784784, -0.24928261,  0.33237682, -0.66475364,
        0.16618841,  1.08022466, -0.33237682, -1.49569568, -0.58165943,
        1.32950727,  0.16618841,  0.99713045,  0.0830942 ,  2.24354352,
        0.99713045, -1.08022466, -0.66475364,  0.99713045,  0.41547102,
       -0.0830942 ,  1.16331886, -1.16331886,  1.08022466, -0.41547102,
       -0.41547102, -0.16618841, -0.49856523, -0.16618841, -0.49

2) A bank issues credit cards in partnership with MASTER CARD. From history 40% of
cardholders do not pay dues on time. Construct a probability distribution of on time
payers for a sample of 7 accounts.

In [10]:
p   =  0.6                # probability of paying on-time
n   =   7                 # no. of trials (no. of customers)
k   =  np.arange(0,7)     # array of outcomes for 7 trials
binom_pmf = stats.binom.pmf(k,n,p) 
print(binom_pmf)

[0.0016384 0.0172032 0.0774144 0.193536  0.290304  0.2612736 0.1306368]


3) A loom produces on the average 2 defects per meter of cloth. What is likely hood that
there is no defect in a 3 meter length?

In [12]:
mu = 3*2
stats.poisson.cdf(0,mu)

0.002478752176666357

4a)
On the average 6 cars arrive every 2 minutes at a petrol station.

i.What is the probability that exactly four cars arriving in 1 minute?

ii.What is the probability of 0 cars arriving in 3 minutes?

iii.What is probability of at least 3 cars arriving in 2 minutes?

In [20]:
k = np.arange(0,7)
a = stats.poisson.pmf(k,3)
b = stats.poisson.pmf(k,9)
c = stats.poisson.cdf(k,6)
print('probability that exactly four cars arriving in 1 minute is %2.4f' %a[4])
print('probability of 0 cars arriving in 3 minutes is %2.4f' %b[0])
print('probability of at least 3 cars arriving in 2 minutes is %2.4f' %(1-c[3]))

probability that exactly four cars arriving in 1 minute is 0.1680
probability of 0 cars arriving in 3 minutes is 0.0001
probability of at least 3 cars arriving in 2 minutes is 0.8488


4b) An airline gets on the average 4 missing baggage claims every day. Construct a probability distribution table for the missing baggage data (15 entries).

i)What is the probability of at least 50 claims a week?

ii)What is the probability of no claim on a day?

iii)What is the probability of at most 10 claims in a 3 day period?.

In [23]:
k=np.arange(0,51)
a=stats.poisson.cdf(k,28)
print('probability of at least 50 claims a week is %2.4f' %(1-a[50]))
b=stats.poisson.pmf(k,4)
print('probability of at least 50 claims a week is %2.4f' %(b[0]))
c=stats.poisson.cdf(k,12)
print('probability of at most 10 claims in a 3-day period is %2.4f' %c[10])

probability of at least 50 claims a week is 0.0001
probability of at least 50 claims a week is 0.0183
probability of at most 10 claims in a 3-day period is 0.3472


5) Using standard normal distribution we can find out probability that z assumes certain
value.
z
Area = Probability

< 1
0.3413 + 0.5 = 0.8413

.>2
0.5000-0.4772 = 0.0228

1 < z < 2
0.4772-0.3413 = 0.1359

<-2 
= > +2 = 0.5000-0.4772 = 0.0228

-1 < z < 0.5 
=0.5 < z < 1 = 0.3413- 0.1915 = 0.1498

-1 < z < 1.5 
= z < 1 + z < 1.5 = 0.3413 + 0.4332 = 0.7745


In [25]:
print ('z < 1: %2.4f' %stats.norm.cdf(1))
print ('z > 2: %2.4f' %(1 - stats.norm.cdf(2)))
print ('1 < z < 2: %2.4f' %(stats.norm.cdf(2) - stats.norm.cdf(1)))
print (' z < -2: %2.4f' %stats.norm.cdf(-2))
print ('-1 < z < -0.5: %2.4f' %(stats.norm.cdf(-.5) - stats.norm.cdf(-1)))
print ('z less than -2 or z > +2: %2.4f' %(2*stats.norm.cdf(-2)))

z < 1: 0.8413
z > 2: 0.0228
1 < z < 2: 0.1359
 z < -2: 0.0228
-1 < z < -0.5: 0.1499
z less than -2 or z > +2: 0.0455


6) The weight of breakfast cereal package follows a normal
distribution with mean of 295 gm and SD of 25 gm What is
the probability that a randomly chosen package weighs

i) <280 gm 
ii) >350 gm 
iii) between 260 and 340 gm


A TV set is likely to fail if the supply voltage is 180 v or more
than 260 v In your locality the line voltage is normally
distributed with a mean of 220 v and SD of 20 v What is the
probability of your TV breaking down?

In [91]:
mu=295
sd=25
a=stats.norm.cdf(280,mu,sd)
print('probability that a randomly chosen package weighs less than 280 gm is %2.4f' %a)
b=1-stats.norm.cdf(350,mu,sd)
print('probability that a randomly chosen package weighs greater than 360 gm is %2.4f ' %b)
c=stats.norm.cdf(340,mu,sd)-stats.norm.cdf(260,mu,sd)
print('probability that a randomly chosen package weighs between 260gm and 360gm is %2.4f' %c)

print()
mu1=220
sd1=20
d=stats.norm.cdf(260,mu1,sd1)-stats.norm.cdf(180,mu1,sd1)
print('probability of your TV breaking down is %2.4f' %(1-d))

probability that a randomly chosen package weighs less than 280 gm is 0.2743
probability that a randomly chosen package weighs greater than 360 gm is 0.0139 
probability that a randomly chosen package weighs between 260gm and 360gm is 0.8833

probability of your TV breaking down is 0.0455


7) A bank wants to study customer perception of quality of its services to savings account
holders. It is decided to go for a sample study. Say there are 1000 account holders and
we want to select 50 a/c holders for the study.

In [30]:
a=np.random.randint(2000,size=1000)
np.random.choice(a,50)

array([ 103, 1978,    0,  939, 1482,   59,  615,  492, 1377,   63, 1295,
       1761,  680,  795,  621,  799, 1910, 1426,  213, 1775, 1351, 1644,
       1887, 1566, 1694,  342,  739, 1051,  791, 1113,  160,  579,  198,
       1082,  823, 1161,  265,  590,  397,  202,  503, 1802, 1550, 1029,
       1450,  269,   34, 1185, 1084, 1849])

8) A sample of 20 girls out of 30 have indicated preference for medicine.
Historically it is known that 70% of girls prefer medicine. Calculate ҧ 𝑝and
𝜎ҧ 𝑝. What is the probability of obtaining ҧ 𝑝value between 0.65 and 0.75.

In [32]:
n=30
p=0.7
pbar=0.65
sigma_p=np.sqrt(p*(1-p))
sigma_pbar=np.sqrt(p*(1-p)/n)
(pbar-p)/sigma_pbar

-0.5976143046671959

In [33]:
n=30
p=0.7
p_bar=0.75
sigmap=np.sqrt(p*(1-p))
sigmapbar=np.sqrt(p*(1-p)/n)
(p_bar-p)/sigmapbar


0.5976143046671972

In [35]:
print('probability of obtaining ҧ 𝑝value between 0.65 and 0.75 is %2.4f' %(stats.norm.cdf(0.59)-stats.norm.cdf(-0.59)))

probability of obtaining ҧ 𝑝value between 0.65 and 0.75 is 0.4448


9) A company is planning to buy a machine that can save significant labour hours. The labour hours
saved by the machine follows a normal distribution. A sample of 36 observations indicated that
on the average it saves 2200 labour hours and that there is a 50% chance that the average labour
hours saved falls above 2400 or below 2000.

a.
What is the population standard deviation?

b.
What is the standard error in estimating the mean?

c.
What is the 95% confidence interval for the mean?

In [90]:
a=np.random.randint(2000,2400,36)
n=36
x_bar=2200
p=0.5
sd=np.std(a)
se=sd/np.sqrt(n)
print('population standard deviation is %2.4f' %sd)
print('standard error is %2.2f' %se)
cl_95=stats.t.ppf(0.025,35)
ci_1=x_bar+(cl_95_t*sd/len(a))
ci_2=x_bar-(cl_95_t*sd/len(a))
print('confidence interval for the mean is %2.2f to %2.2f' %((ci_2),(ci_1)))

population standard deviation is 113.3122
standard error is 18.89
confidence interval for the mean is 2193.41 to 2206.59


10) A computer aided training program is expected to reduce the s/w
project completion time. A sample of 20 project completion times is
given. Develop a 95% Confidence interval for the mean completion
time.

1-52
2-44
3-55
4-44
5-45
6-59
7-50
8-54
9-62
10-46
11-54
12-42
13-60
14-62
15-43
16-42
17-48
18-55
19-57
20-56

In [53]:
a=[52,44,55,44,45,59,50,54,62,46,54,42,60,62,43,42,48,55,57,56]
b=pd.DataFrame(a)
b.index=b.index+1
x_bar=b.mean().values[0]
std=b.std().values[0]
cl_95_t=abs(stats.t.ppf(0.025,19))
ci_1=x_bar+(cl_95_t*std/len(b))
ci_2=x_bar-(cl_95_t*std/len(b))
print('confidence interval for the mean completion time is %2.2f to %2.2f' %((ci_2),(ci_1)))

confidence interval for the mean completion time is 50.78 to 52.22


11) In 2012, NDTV survey of 814 adults indicated that 562
adults expect Pranab Mukherjee to win the Presidential
election. What proportion of Indian adults thought
Pranab would win? What was the margin of error? Use
95% confidence level.

Distractors argued that the margin of error and
confidence intervals were too big. If you want to limit
the error to 1% at 99% confidence what should be the
sample size?

In [62]:
n=814
p_bar=562/814
sigma=np.sqrt(p_bar*(1-p_bar))
sigma_p=sigma/np.sqrt(n)
mu1=p_bar+(1.96*sigma_p)
mu2=p_bar-(1.96*sigma_p)
error=(1.96)*sigma_p
print('proportion of Indian adults who thought Pranab would win is %2.2f percent' %(p_bar*100))
print('margin of error is %2.2f percent' %(error*100))

proportion of Indian adults who thought Pranab would win is 69.04 percent
margin of error is 3.18 percent


In [67]:
cl_98=2.58
error=1/100
k=np.square(cl_98*sigma_p/error)
print(' If the error is limited to 1 percent at 99 percent confidence, the sample size should be %2.0f' %k)

 If the error is limited to 1 percent at 99 percent confidence, the sample size should be 17
